model_class: DECODER

reduced_rank:
  temporal_rank: 2
  global_basis_rank: 10

mlp:
  mlp_hidden_size: (256, 128, 64)
  drop_out: 0.1

lstm:
  lstm_n_layers: 3
  lstm_hidden_size: 256
  mlp_hidden_size: (128, 64)
  drop_out: 0.1
  