model_class: DECODER

reduced_rank:
  temporal_rank: 30
  global_basis_rank: 2

mlp:
  mlp_hidden_size: (512, 256, 128, 64)
  drop_out: 0.02
  n_layers: 4
  hidden_dim: 460

lstm:
  lstm_n_layers: 3
  lstm_hidden_size: 256
  mlp_hidden_size: (128, 64)
  drop_out: 0.1
