seed: 42

dirs:
  checkpoint_dir: checkpoints  
  log_dir: train_logs  
  data_dir: cached_ibl_data
  output_dir: results

training:
  num_epochs: 500
  batch_size: 8

  device: cpu
  metric: val_loss
  mode: min
  enable_progress_bar: true
  load_local: true

model: 
  model_class: DECODER   
  target: reg            
  output_size: 100       

data:
  dataset_class: decoding 

  train_name: train   
  test_name: test     
  train_len: null     
  test_len: null      

  num_workers: 1

optimizer:
  lr: 0.01
  scheduler: cosine  # step/cosine/linear
  weight_decay: 0.1

tuner:
  num_epochs: 10     # increase if running on hpc
  num_samples: 1
  use_gpu: false
  num_workers: 1
  metric: val_loss
  mode: min
  enable_progress_bar: false

